import { useDeferredValue, useEffect, useMemo, useRef, useState } from "react";
import { BookMarked, BookOpen, Check, Download, ExternalLink, FileUp, Library, LoaderCircle, Search, Settings2 } from "lucide-react";
import { api } from "../../api";
import type { GutenbergBook, ReadingBook, ReadingLibraryData } from "../../types";
import { demoReadingLibrary } from "./demoReading";
import { ReaderView } from "./ReaderView";

type Tab = "shelf" | "curated" | "online";
export function ReadingStudy({ demo }: { demo: boolean }) {
  const [data, setData] = useState<ReadingLibraryData | null>(() => demo ? demoReadingLibrary : null);
  const [activeBook, setActiveBook] = useState<string | null>(null); const [tab, setTab] = useState<Tab>("shelf");
  const [query, setQuery] = useState(""); const deferredQuery = useDeferredValue(query); const [online, setOnline] = useState<GutenbergBook[]>([]);
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(!demo); const [jobs, setJobs] = useState<Array<{ id: string; bookId: string; status: string; progress: number; errorCode: string | null; createdAt: string }> | null>(null); const inputRef = useRef<HTMLInputElement>(null);
  const refresh = () => { if (demo) return; setLoading(true); api.readingLibrary().then(setData).catch((error: Error) => setMessage(error.message)).finally(() => setLoading(false)); };
  useEffect(refresh, [demo]);
  const visible = useMemo(() => { const books = data?.books ?? []; const needle = deferredQuery.trim().toLocaleLowerCase(); return books.filter((book) => (tab === "shelf" ? book.visibility === "private" || book.shelved : tab === "curated" ? book.visibility !== "private" : false) && (!needle || `${book.title} ${book.titleZh ?? ""} ${book.author ?? ""}`.toLocaleLowerCase().includes(needle))); }, [data, deferredQuery, tab]);
  if (activeBook) return <ReaderView bookId={activeBook} demo={demo} onClose={() => { setActiveBook(null); refresh(); }} />;
  const continuing = data?.books.find((book) => book.id === data.continueReading);
  const upload = async (file?: File) => { if (!file) return; try { setMessage(`正在导入 ${file.name}…`); if (demo) { setMessage("预览模式不会保存文件"); return; } await api.uploadReadingBook(file); setMessage("文件已上传，正在解析"); refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "导入失败"); } };
  const searchOnline = async () => { if (!query.trim()) return; try { setMessage("正在查询 Project Gutenberg…"); setOnline(demo ? [{ id: "55", title: "The Wonderful Wizard of Oz", author: "L. Frank Baum", downloadUrl: null, sourceUrl: "https://www.gutenberg.org/ebooks/55" }] : (await api.searchReadingCatalog(query)).books); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "在线书库不可用"); } };
  const addOnline = async (book: GutenbergBook) => { try { setMessage(`正在把《${book.title}》加入书架…`); if (!demo) await api.addReadingCatalogBook(book); setMessage("已加入书架，后台正在解析"); setTab("shelf"); refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "加入书架失败"); } };
  const showAdmin = async () => { try { setJobs(demo ? [] : (await api.readingAdminJobs()).jobs); } catch (error) { setMessage(error instanceof Error ? error.message : "管理数据加载失败"); } };
  if (loading) return <section className="reading-state"><LoaderCircle className="spin" />正在整理书架…</section>;
  if (!data) return <section className="reading-state error">{message || "阅读模块暂时不可用"}</section>;
  return <div className="reading-library">
    <div className="reading-actions"><label className="reading-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索书名或作者" onKeyDown={(event) => { if (event.key === "Enter" && tab === "online") void searchOnline(); }} /></label><button className="reading-outline-button" onClick={() => inputRef.current?.click()}><FileUp size={18} />导入书籍</button><button className="reading-primary-button" onClick={() => setTab("online")}><Library size={18} />在线书库</button><input ref={inputRef} hidden type="file" accept=".epub,.pdf,.txt,.mobi,.azw,.azw3,.fb2,.html,.htm,.md,.markdown,.docx,.rtf" onChange={(event) => void upload(event.target.files?.[0])} /></div>
    {message ? <p className="reading-message" role="status">{message}</p> : null}
    {continuing ? <section className="continue-reading"><BookCover book={continuing} /><div><small>继续阅读</small><h2>{continuing.title}</h2><p>{continuing.author} · {continuing.currentChapter + 1} / {Math.max(continuing.chapterCount, 1)} 章</p><Progress value={continuing.progress} /></div><button onClick={() => setActiveBook(continuing.id)}>继续阅读<BookOpen size={18} /></button></section> : null}
    <div className="reading-tabs"><div><button className={tab === "shelf" ? "active" : ""} onClick={() => setTab("shelf")}>我的书架</button><button className={tab === "curated" ? "active" : ""} onClick={() => setTab("curated")}>精选书库</button><button className={tab === "online" ? "active" : ""} onClick={() => setTab("online")}>在线搜索</button></div><span>{data.quota.books} / {data.quota.maxBooks} 本 · {formatBytes(data.quota.bytes)} / {formatBytes(data.quota.maxBytes)}</span>{data.role === "admin" ? <button className="admin-library-button" onClick={() => void showAdmin()}><Settings2 size={17} />管理书库</button> : null}</div>
    {tab === "online" ? <section className="online-library"><div className="online-search-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="输入英文书名或作者" /><button onClick={() => void searchOnline()}><Search size={17} />搜索</button></div>{online.map((book) => <article key={book.id}><BookMarked /><div><h3>{book.title}</h3><p>{book.author || "未知作者"} · Project Gutenberg #{book.id}</p></div>{book.sourceUrl ? <a href={book.sourceUrl} target="_blank" rel="noreferrer">查看来源<ExternalLink size={15} /></a> : null}<button onClick={() => void addOnline(book)}>加入书架</button></article>)}</section> : <section className="book-grid">{visible.map((book) => <BookCard key={book.id} book={book} onOpen={() => book.status === "ready" ? setActiveBook(book.id) : setMessage(book.status === "protected" ? "该书受 DRM 保护，需要版权方授权" : "书籍仍在解析，请稍后再试")} onAdd={tab === "curated" && book.visibility === "curated" && !book.shelved && book.externalId ? () => void addOnline({ id: book.externalId!, title: book.title, author: book.author ?? "", downloadUrl: null, sourceUrl: `https://www.gutenberg.org/ebooks/${book.externalId}` }) : undefined} />)}{!visible.length ? <div className="reading-empty"><BookOpen /><h3>这里还没有书</h3><p>导入一本无 DRM 电子书，或从精选书库开始。</p></div> : null}</section>}
    {jobs ? <div className="reading-admin-modal" role="dialog" aria-modal="true"><section><header><div><small>仅显示处理状态，不显示用户书籍内容</small><h2>阅读书库任务</h2></div><button onClick={() => setJobs(null)}>关闭</button></header>{jobs.length ? jobs.map((job) => <article key={job.id}><code>{job.bookId.slice(0, 8)}</code><strong>{job.status}</strong><span>{job.progress}%</span><small>{job.errorCode || new Date(job.createdAt).toLocaleString()}</small></article>) : <p>当前没有导入任务。</p>}</section></div> : null}
  </div>;
}

function BookCard({ book, onOpen, onAdd }: { book: ReadingBook; onOpen: () => void; onAdd?: (() => void) | undefined }) { return <article className="book-card"><button className="book-card-open" onClick={onOpen}><BookCover book={book} /><span className="book-card-copy"><strong>{book.title}</strong><small>{book.titleZh}</small><em>{book.author}</em>{book.status === "ready" ? <><Progress value={book.progress} /><small>{book.progress ? `已读 ${Math.round(book.progress)}%` : `${difficultyLabel(book.difficulty)} · 约 ${book.cefrHint ?? "待估算"}`}</small></> : <span className={`book-status ${book.status}`}><LoaderCircle size={14} />{book.status === "protected" ? "受 DRM 保护" : book.status === "failed" ? "解析失败" : "正在解析"}</span>}</span></button>{onAdd ? <button className="book-card-add" onClick={onAdd}><Download size={15} />加入书架</button> : null}</article>; }
function BookCover({ book }: { book: ReadingBook }) { const palette = Number.parseInt(book.id.replace(/\D/g, "").slice(-2) || "4") % 4; return <span className={`reading-cover palette-${palette}`}><BookOpen /><b>{book.title}</b><small>{book.author}</small></span>; }
function Progress({ value }: { value: number }) { return <span className="reading-progress"><i style={{ width: `${Math.max(3, value)}%` }} /></span>; }
function difficultyLabel(value: ReadingBook["difficulty"]) { return value === "entry" ? "入门" : value === "intermediate" ? "进阶" : value === "challenge" ? "挑战" : "待分级"; }
function formatBytes(value: number) { return value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(value >= 10 * 1024 ** 3 ? 0 : 1)} GB` : `${Math.round(value / 1024 ** 2)} MB`; }
