import { Fragment, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Bookmark, BookOpen, Check, ChevronLeft, Download, Highlighter, Languages, Library, List, Minus, Moon, NotebookPen, Plus, Search, Settings2, Sun, X } from "lucide-react";
import { api } from "../../api";
import type { ReadingAnnotation, ReadingBookDetail, ReadingLookupResult, ReadingPreferences } from "../../types";
import { PronunciationLine } from "../vocabulary/PronunciationLine";
import { demoReadingBook } from "./demoReading";
import { cacheReadingBook, cachedReadingBook } from "./offline";
import { selectSentenceAt, tokenizeWithOffsets } from "./sentence-selection";

export function ReaderView({ bookId, demo, onClose }: { bookId: string; demo: boolean; onClose: () => void }) {
  const [detail, setDetail] = useState<ReadingBookDetail | null>(() => demo ? demoReadingBook : null); const [chapterIndex, setChapterIndex] = useState(0);
  const [lookup, setLookup] = useState<ReadingLookupResult | null>(null); const [lookupPending, setLookupPending] = useState(false); const [selectedSentence, setSelectedSentence] = useState("");
  const [translation, setTranslation] = useState(""); const [message, setMessage] = useState(""); const [showContents, setShowContents] = useState(true); const [showNotes, setShowNotes] = useState(true); const [showSearch, setShowSearch] = useState(false); const [searchQuery, setSearchQuery] = useState(""); const articleRef = useRef<HTMLElement>(null);
  useEffect(() => { if (demo) return; api.readingBook(bookId).then((value) => { setDetail(value); setChapterIndex(value.book.currentChapter); void cacheReadingBook(value); }).catch(async (error: Error) => { const cached = await cachedReadingBook(bookId); if (cached) { setDetail(cached); setChapterIndex(cached.book.currentChapter); setMessage("当前为离线阅读"); } else setMessage(error.message); }); }, [bookId, demo]);
  const chapter = detail?.manifest?.chapters[chapterIndex]; const preferences = detail?.book.preferences ?? defaultPreferences;
  const progress = detail?.manifest ? ((chapterIndex + 1) / detail.manifest.chapters.length) * 100 : 0;
  useEffect(() => { if (!detail || demo) return; const timer = window.setTimeout(() => void api.saveReadingProgress(bookId, { chapterIndex, offset: articleRef.current?.scrollTop ?? 0, progress, preferences: detail.book.preferences }), 650); return () => window.clearTimeout(timer); }, [bookId, chapterIndex, detail, demo, progress]);
  const annotations = useMemo(() => detail?.annotations.filter((item) => item.chapterIndex === chapterIndex) ?? [], [detail, chapterIndex]);
  const searchResults = useMemo(() => { const needle = searchQuery.trim().toLocaleLowerCase(); if (!needle || !detail?.manifest) return []; return detail.manifest.chapters.flatMap((item, index) => { const position = item.text.toLocaleLowerCase().indexOf(needle); if (position < 0) return []; return [{ chapterIndex: index, title: item.title, excerpt: item.text.slice(Math.max(0, position - 70), Math.min(item.text.length, position + needle.length + 110)).replace(/\s+/g, " ") }]; }).slice(0, 30); }, [detail, searchQuery]);
  const setPreferences = (patch: Partial<ReadingPreferences>) => setDetail((current) => current ? { ...current, book: { ...current.book, preferences: { ...current.book.preferences, ...patch } } } : current);
  const selectWord = async (term: string) => { setLookupPending(true); setTranslation(""); try { setLookup(demo ? { term, lemma: term.toLowerCase(), pronunciation: { status: "verified", us: { ipa: "/ˈkɜːrɪdʒ/", alternatives: [], audioUrl: null }, uk: { ipa: "/ˈkʌrɪdʒ/", alternatives: [], audioUrl: null }, parts: [] }, meanings: [{ partOfSpeech: "noun", definition: "勇气；胆量" }], source: "演示词典" } : await api.lookupReadingTerm(term)); } catch (error) { setMessage(error instanceof Error ? error.message : "查词失败"); } finally { setLookupPending(false); } };
  const translate = async (text: string) => { if (!text.trim()) return; try { setTranslation(demo ? "不要害怕我，狼说道，我并没有看起来那么凶猛。" : (await api.translateReadingText(text)).translation); } catch (error) { setMessage(error instanceof Error ? error.message : "翻译失败"); } };
  const addVocabulary = async () => { if (!lookup || !chapter || !detail) return; const meaning = lookup.meanings[0]?.definition ?? "释义待补全"; try { if (!demo) await api.addReadingVocabulary({ term: lookup.lemma, meaning, bookId, chapterIndex, sourceForm: lookup.term, quote: selectedSentence || selectSentenceAt(chapter.text, chapter.text.toLowerCase().indexOf(lookup.term.toLowerCase())), startOffset: 0 }); setMessage("已加入生词本，并保存当前出处"); } catch (error) { setMessage(error instanceof Error ? error.message : "生词保存失败"); } };
  const addAnnotation = async (kind: ReadingAnnotation["kind"], quote: string, note?: string) => { if (!detail) return; const draft = { chapterIndex, kind, startOffset: 0, endOffset: quote.length, quote, note: note ?? null, color: "green" }; const saved = demo ? { ...draft, id: crypto.randomUUID(), bookId, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() } : await api.addReadingAnnotation(bookId, draft); setDetail({ ...detail, annotations: [saved, ...detail.annotations] }); };
  const exportAnnotations = () => { if (!detail) return; const blob = new Blob([JSON.stringify({ book: detail.book.title, exportedAt: new Date().toISOString(), annotations: detail.annotations }, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${detail.book.title.replace(/[^\p{L}\p{N}._-]+/gu, "-")}-阅读笔记.json`; link.click(); window.setTimeout(() => URL.revokeObjectURL(link.href), 1_000); };
  if (!detail) return <main className="reader-loading"><BookOpen /><p>{message || "正在打开书籍…"}</p><button onClick={onClose}>返回书架</button></main>;
  if (!detail.manifest || !chapter) return <main className="reader-loading"><BookOpen /><h1>{detail.book.title}</h1><p>{detail.book.status === "protected" ? "该文件受 DRM 保护，需要版权方官方授权后才能阅读。" : "书籍仍在解析，完成后即可阅读。"}</p><button onClick={onClose}>返回书架</button></main>;
  return <main className={`ebook-reader theme-${preferences.theme} mode-${preferences.mode}`}>
    <header className="reader-toolbar"><button onClick={onClose}><ArrowLeft /><span>返回书架</span></button><div><strong>{detail.book.title}</strong><span>{chapterIndex + 1} / {detail.manifest.chapters.length} 章</span></div><nav><button onClick={() => setShowContents((value) => !value)}><List />目录</button><button onClick={() => setShowSearch((value) => !value)}><Search />搜索</button><button onClick={() => void addAnnotation("bookmark", chapter.title)}><Bookmark />书签</button><button onClick={() => setShowNotes((value) => !value)}><NotebookPen />笔记</button><button title="排版选项位于底部工具栏"><Settings2 />排版</button></nav></header>
    <div className="reader-workspace">
      {showContents ? <aside className="reader-contents"><div><strong>目录</strong><button onClick={() => setShowContents(false)}><ChevronLeft /></button></div>{detail.manifest.chapters.map((item, index) => <button key={`${index}-${item.title}`} className={index === chapterIndex ? "active" : ""} onClick={() => { setChapterIndex(index); setLookup(null); }}><span>{roman(index + 1)}.</span>{item.title}</button>)}</aside> : null}
      <section className="reader-canvas"><article ref={articleRef} tabIndex={-1} className="reader-article" style={{ fontSize: `${preferences.fontScale}em`, lineHeight: preferences.lineHeight }} onMouseUp={() => { const text = window.getSelection()?.toString().trim() ?? ""; if (text.split(/\s+/).length > 1 && text.length <= 2_000) setSelectedSentence(text); }}>
        <h1>{chapter.title}</h1><div className="chapter-ornament"><i /><b /><i /></div>{chapter.text.split(/\n\s*\n/).map((paragraph, index) => <p key={index}>{tokenizeWithOffsets(paragraph).map((token, tokenIndex) => token.isWord ? <span key={tokenIndex} className={lookup?.term.toLowerCase() === token.text.toLowerCase() ? "reader-word selected" : "reader-word"} onDoubleClick={() => { setSelectedSentence(selectSentenceAt(paragraph, token.startOffset)); void selectWord(token.text); }} onContextMenu={(event) => { event.preventDefault(); setSelectedSentence(selectSentenceAt(paragraph, token.startOffset)); void selectWord(token.text); }}>{token.text}</span> : <Fragment key={tokenIndex}>{token.text}</Fragment>)}</p>)}
        {translation ? <aside className="inline-translation"><Languages />{translation}<button onClick={() => void addAnnotation("translation", selectedSentence, translation)}>保存译文</button></aside> : null}
      </article>
      {selectedSentence ? <div className="selection-toolbar"><button onClick={() => void selectWord(selectedSentence)}><Search />查询短语</button><button onClick={() => void translate(selectedSentence)}><Languages />翻译所选</button><button onClick={() => void addAnnotation("highlight", selectedSentence)}><Highlighter />划线</button><button onClick={() => setSelectedSentence("")}><X /></button></div> : null}
      {lookup || lookupPending ? <aside className="lookup-card"><button className="lookup-close" onClick={() => setLookup(null)}><X /></button>{lookupPending ? <p>正在查询…</p> : lookup ? <><h2>{lookup.term}</h2>{lookup.lemma !== lookup.term.toLowerCase() ? <small>原形　{lookup.lemma}</small> : null}{lookup.pronunciation ? <PronunciationLine pronunciation={lookup.pronunciation} /> : null}<div className="lookup-meanings">{lookup.meanings.length ? lookup.meanings.map((item, index) => <p key={index}><em>{item.partOfSpeech}</em>{item.definition}</p>) : <p>本地词典暂无释义</p>}</div><blockquote>{selectedSentence}</blockquote><footer><button onClick={() => void translate(selectedSentence)}><Languages />翻译整句</button><button onClick={() => void addVocabulary()}><Library />加入生词本</button></footer></> : null}</aside> : null}</section>
      {showNotes ? <aside className="reader-notes"><div><strong>笔记与划线</strong><button onClick={() => setShowNotes(false)}><X /></button></div>{annotations.map((annotation) => <article key={annotation.id}><small>{annotation.kind === "note" ? "笔记" : annotation.kind === "translation" ? "译文" : annotation.kind === "bookmark" ? "书签" : "划线"}</small><p>{annotation.quote}</p>{annotation.note ? <blockquote>{annotation.note}</blockquote> : null}</article>)}{!annotations.length ? <p className="reader-notes-empty">选中文字后可以划线、翻译或保存笔记。</p> : null}<button className="new-note" onClick={() => void addAnnotation("note", selectedSentence || chapter.title, "新笔记")}>＋ 新建笔记</button><button className="export-notes" onClick={exportAnnotations}><Download />导出全部笔记</button></aside> : null}
    </div>
    {showSearch ? <aside className="reader-search-panel"><header><Search /><input autoFocus value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} placeholder="搜索整本书" /><button onClick={() => setShowSearch(false)}><X /></button></header>{searchQuery && !searchResults.length ? <p>没有找到匹配内容。</p> : searchResults.map((result) => <button key={`${result.chapterIndex}-${result.excerpt}`} onClick={() => { setChapterIndex(result.chapterIndex); setShowSearch(false); }}><strong>{result.title}</strong><span>…{result.excerpt}…</span></button>)}</aside> : null}
    <footer className="reader-footer"><div className="chapter-progress"><span>本章进度</span><i><b style={{ width: `${progress}%` }} /></i><strong>{Math.round(progress)}%</strong></div><button disabled={chapterIndex === 0} onClick={() => setChapterIndex((value) => Math.max(0, value - 1))}>上一章</button><button className="next" disabled={chapterIndex >= detail.manifest.chapters.length - 1} onClick={() => setChapterIndex((value) => Math.min(detail.manifest!.chapters.length - 1, value + 1))}>下一章</button><div className="reader-display-controls"><button className={preferences.mode === "scroll" ? "active" : ""} onClick={() => setPreferences({ mode: "scroll" })}>滚动</button><button className={preferences.mode === "paged" ? "active" : ""} onClick={() => setPreferences({ mode: "paged" })}>翻页</button><button onClick={() => setPreferences({ fontScale: Math.max(.8, preferences.fontScale - .1) })}><Minus /></button><span>字号</span><button onClick={() => setPreferences({ fontScale: Math.min(1.5, preferences.fontScale + .1) })}><Plus /></button><button onClick={() => setPreferences({ theme: preferences.theme === "dark" ? "paper" : "dark" })}>{preferences.theme === "dark" ? <Sun /> : <Moon />}主题</button></div></footer>
    {message ? <div className="reader-toast" role="status"><Check />{message}<button onClick={() => setMessage("")}><X /></button></div> : null}
  </main>;
}

const defaultPreferences: ReadingPreferences = { mode: "scroll", fontScale: 1, lineHeight: 1.9, theme: "paper", publisherStyles: false };
function roman(value: number) { const rows: Array<[number, string]> = [[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]]; let current = value; let result = ""; for (const [number, symbol] of rows) while (current >= number) { result += symbol; current -= number; } return result; }
